export const ADD_NEW_BUSINESS_CATEGORY = 'ADD_NEW_BUSINESS_CATEGORY';
export const ADD_NEW_BUSINESS_CATEGORY_GET = 'ADD_NEW_BUSINESS_CATEGORY_GET';
export const ADD_NEW_BUSINESS_TYPE = 'ADD_NEW_BUSINESS_TYPE';
export const ADD_HOUSE_DELIVERY = 'ADD_HOUSE_DELIVERY';
export const ADD_OPEN_STATUS = 'ADD_OPEN_STATUS';
export const ADD_ALCOHOL = 'ADD_ALCOHOL';
